### ISSUE TITLE
Please, provide a Fluentbit's package for Fedora

### ISSUE THREAD

**Issue by q2dg** [fluent/fluent-bit-packaging#25]
I've open an issue about this here: https://github.com/fluent/fluent-bit/issues/4356 but maybe this is the best place
Thanks and sorry for the inconvenience

**Comment by modem7** [comment]
As a continuation from https://github.com/fluent/fluent-bit/issues/4356#issuecomment-1042308693

Fedora 38:

```
sudo dnf repoquery --requires --resolve td-agent-bit
Last metadata expiration check: 0:00:08 ago on Mon Nov 21 16:17:31 2022.
bash-0:5.2.9-3.fc38.x86_64
glibc-0:2.36.9000-13.fc38.i686
glibc-0:2.36.9000-13.fc38.x86_64
libgcc-0:12.2.1-3.fc38.x86_64
systemd-libs-0:252.1-588.fc38.x86_64
zlib-0:1.2.12-5.fc38.x86_64
```

```
Error:
 Problem: conflicting requests
  - nothing provides libcrypto.so.10()(64bit) needed by td-agent-bit-1.3.11-1.x86_64
  - nothing provides libcrypto.so.10(libcrypto.so.10)(64bit) needed by td-agent-bit-1.3.11-1.x86_64
  - nothing provides libssl.so.10()(64bit) needed by td-agent-bit-1.3.11-1.x86_64
  - nothing provides libssl.so.10(libssl.so.10)(64bit) needed by td-agent-bit-1.3.11-1.x86_64
```

Please ignore the above - just read the doco:
https://docs.fluentbit.io/manual/installation/linux#migration-to-fluent-bit

`dnf -y install fluent-bit` works.

**Comment by edsiper** [comment]
cc: @patrick-stephens

**Comment by patrick-stephens** [comment]
Sure, I mean it'll be a lot faster with a PR. However looking at the comment above it seems the issue is that people were installing the no longer provided `td-agent-bit` but `fluent-bit` works ok.

> Please ignore the above - just read the doco:
> https://docs.fluentbit.io/manual/installation/linux#migration-to-fluent-bit
> 
> dnf -y install fluent-bit works.

All the packaging is here: https://github.com/fluent/fluent-bit/tree/master/packaging
The `./packaging/build.sh -d <distro>` script is used to run containerised builds for each target here: https://github.com/fluent/fluent-bit/tree/master/packaging/distros

See the recent PR for adding Debian Bookworm support for an example of how to do so: https://github.com/fluent/fluent-bit/pull/6409

Note that Amazon Linux 2022 support is already provided as well.

@edsiper we should archive this repo as it's no longer used.

**Comment by patrick-stephens** [comment]
@modem7 are we ok to close, it sounds like it is working?

**Comment by modem7** [comment]
> @modem7 are we ok to close, it sounds like it is working?

Yupper! Looks all good my end!

Thanks!!
